/* Generated By IA */

declare module "localbase" {
  /**
   * Localbase - A powerful IndexedDB wrapper with a simple API
   */
  export default class Localbase {
    constructor(dbName: string);

    /**
     * Seleciona uma coleção do banco de dados
     * @param collectionName Nome da coleção
     * @returns Instância de Collection com tipagem genérica
     */
    collection<T = unknown>(collectionName: string): Collection<T>;

    /**
     * Deleta todo o banco de dados
     */
    delete(): Promise<void>;
  }

  /**
   * Representa uma coleção no banco de dados
   */
  interface Collection<T> {
    /**
     * Adiciona um novo documento à coleção
     * @param document Documento a ser adicionado
     * @param customKey Chave
     */
    add(document: T, customKey?: string): Promise<void>;

    /**
     * Deleta todos os documentos da coleção
     */
    delete(): Promise<void>;

    /**
     * Seleciona um documento específico da coleção
     * @param criteria Critérios para encontrar o documento
     */
    doc(criteria: Partial<T>): Document<T>;

    /**
     * Retorna todos os documentos da coleção
     */
    get(): Promise<T[]>;

    /**
     * Limita o número de documentos retornados
     * @param count Número máximo de documentos
     */
    limit(count: number): CollectionQuery<T>;

    /**
     * Ordena os documentos por um campo específico
     * @param field Campo para ordenação
     * @param direction Direção da ordenação ('asc' ou 'desc')
     */
    orderBy<K extends keyof T>(
      field: K,
      direction?: "asc" | "desc",
    ): CollectionQuery<T>;
  }

  /**
   * Representa um documento específico na coleção
   */
  interface Document<T> {
    /**
     * Deleta o documento
     */
    delete(): Promise<void>;

    /**
     * Retorna o documento
     */
    get(): Promise<null | T>;

    /**
     * Define/substitui completamente o documento
     * @param document Novo documento
     */
    set(document: T): Promise<void>;

    /**
     * Atualiza parcialmente o documento
     * @param updates Campos a serem atualizados
     */
    update(updates: Partial<T>): Promise<void>;
  }

  /**
   * Representa uma query com métodos de ordenação e limite
   */
  interface CollectionQuery<T> {
    /**
     * Deleta todos os documentos da query
     */
    delete(): Promise<void>;

    /**
     * Retorna os documentos filtrados/ordenados
     */
    get(): Promise<null | T[]>;

    /**
     * Limita o número de documentos retornados
     * @param count Número máximo de documentos
     */
    limit(count: number): CollectionQuery<T>;

    /**
     * Ordena os documentos por um campo específico
     * @param field Campo para ordenação
     * @param direction Direção da ordenação ('asc' ou 'desc')
     */
    orderBy<K extends keyof T>(
      field: K,
      direction?: "asc" | "desc",
    ): CollectionQuery<T>;
  }
}
